### ISSUE TITLE
메인페이지 버튼 생성

### ISSUE THREAD

**Issue by sangzun-han** [HHFEHH/crack-automation#25]
`신규` : 새로운 데이터 등록 
`기존` : category 페이지로 이동
`분석` : categoryDetail 페이지로 이동

**Comment by d9249** [comment]
분석에 CategoryDetail의 crack.id 지정을 할 필요성이 없다.

다른 방안을 고려해야한다.
1. 분석 페이지 생성
2. 아무런 CategoryDetail Page 등록? > 아무런 의미가 없다.
