### ISSUE TITLE
카테고리 페이지 버튼

### ISSUE THREAD

**Issue by sangzun-han** [HHFEHH/crack-automation#27]
1. `건물 정보` --> `시설물 정보` 변경
2. `층별 정보` --> `손상 정보` 변경
3. `보고서 생성` 버튼 생성

4. `수정` 버튼을 `시설물 정보`에서 할 수 있도록 함
5. `전경도`, `위치도` 수정 가능하도록

**Comment by d9249** [comment]
현재 기존 등록되었던 이미지를 불러오지 못하고, 두 개의 이미지를 함께 등록해야 수정이 가능.

1. 기존 이미지 불러오기
2. 한개의 이미지만 수정할 수 있도록.
